### ISSUE TITLE
Glide加载问题

### ISSUE THREAD

**Issue by tdxtxt** [VeiZhang/ImageLoader#1]
glide v4中Generated API需要使用注解器，以下是官网上的说明：
```
Generated API 目前仅可以在 Application 模块内使用。这一限制可以让我们仅持有一份 Generated API，而不是各个 Library 和 Application 中均有自己定义出来的 Generated API。
```
该项目是以lib的形式使用Generated API，这恐怕有问题吧

**Comment by VeiZhang** [comment]
@tdxtxt 官方的意思是保证一个单例对象。你说的问题是指？

**Comment by tdxtxt** [comment]
我测试了，只能在application里面配置```annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'```
在lib中配置会编译失败。

**Comment by VeiZhang** [comment]
@tdxtxt sample示例运行有问题？

**Comment by tdxtxt** [comment]
@VeiZhang 我自己写的demo，是我自己的原因哈，不是你的问题，我没理解好Glide在library中的使用。
